import os

PERSONAL_API_USERNAME = os.getenv("PERSONAL_API_USERNAME")
PERSONAL_API_PASS = os.getenv("PERSONAL_API_USERNAME")

# must be a postgres instance
SQLALCHEMY_DATABASE_URL = os.getenv("PERSONAL_API_SQLALCHEMY_DATABASE_URL")